### ISSUE TITLE
2.2.9 checklist

### ISSUE THREAD

**Issue by Lactozilla** [Lactozilla/SRB2-Android#1]
- [x] Improve and finish the touch screen menus
    - [x] Finish the sound test menu
    - [x] Finish the extras checklist menu
    - [x] Finish the statistics menu
    - [x] Finish the player setup menus
- [x] Finish GLES2 implementation
    - [x] Fix fade mask shaders
    - [x] Fix sky domes
    - [x] Implement alpha testing
    - [x] Fix models
- [x] Fix that thing that OpenGL does
- [x] Finish Android TV support
    - [x] Improve breadcrumb navigation
    - [x] Fix the on-screen keyboard
- [x] Resolve app storage / shared storage confusion
- [x] Revise default settings
- [x] Merge 2.2.9
- [x] Change the app version
- [x] Test on hardware, emulator, Android TV
